/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.web3j.klaytnprotocol;

import org.junit.Test;
import org.web3j.protocol.core.methods.response.NetVersion;
import org.web3j.protocol.http.HttpService;

import java.io.IOException;
import java.math.BigDecimal;

import caver.sdk.apis.KlayApi;
import caver.sdk.models.GetRewardsResponse;

public class Web3jTest {
    @Test public void testSomeLibraryMethod() throws IOException {
        Web3j klaytnWeb3j = new Web3j(new HttpService("http://127.0.0.1:8551"));
        NetVersion nv = klaytnWeb3j.netVersion().send();
        System.out.println(nv.getResult());
    }

    @Test public void testSomeLibraryMethod2() throws IOException {
        KlayApi klaytnWeb3j = new KlayApi(new HttpService("http://127.0.0.1:8551"));
        GetRewardsResponse nv = klaytnWeb3j.getRewards(new BigDecimal(10)).send();
        System.out.println(nv.getResult());
    } 
}
